import type { RebirthUpgrade } from '../game/types';

/**
 * The Core Fragment upgrade tree. Bought with the meta-currency earned on
 * Rebirth. These persist forever, so a run is never truly "lost" — it is
 * converted into permanent power.
 */
export const REBIRTH_UPGRADES: RebirthUpgrade[] = [
  {
    id: 'global-mult',
    name: 'Harmonic Overtone',
    description: '+25% global production per level (multiplicative).',
    effect: 'globalMult',
    perLevel: 0.25,
    baseCost: 1,
    costGrowth: 1.6,
    maxLevel: 200,
    icon: '◈',
  },
  {
    id: 'click-mult',
    name: 'Kinetic Focus',
    description: '×2 click power per level.',
    effect: 'clickMult',
    perLevel: 1,
    baseCost: 2,
    costGrowth: 1.9,
    maxLevel: 40,
    icon: '⊙',
  },
  {
    id: 'start-energy',
    name: 'Warm Start',
    description: 'Begin each run with more banked energy (×10 per level).',
    effect: 'startEnergy',
    perLevel: 1,
    baseCost: 3,
    costGrowth: 2.2,
    maxLevel: 30,
    icon: '↯',
  },
  {
    id: 'milestone-power',
    name: 'Milestone Resonance',
    description: '+10% to every milestone multiplier per level.',
    effect: 'milestonePower',
    perLevel: 0.1,
    baseCost: 5,
    costGrowth: 2.4,
    maxLevel: 25,
    icon: '⬢',
  },
  {
    id: 'crit-chance',
    name: 'Fractal Luck',
    description: '+2% base critical chance per level.',
    effect: 'critChance',
    perLevel: 0.02,
    baseCost: 4,
    costGrowth: 2.0,
    maxLevel: 25,
    icon: '✦',
  },
  {
    id: 'crit-mult',
    name: 'Overload Yield',
    description: '+0.5 to critical multiplier per level.',
    effect: 'critMult',
    perLevel: 0.5,
    baseCost: 6,
    costGrowth: 2.1,
    maxLevel: 20,
    icon: '✸',
  },
  {
    id: 'offline-eff',
    name: 'Dormant Reactor',
    description: '+8% offline efficiency per level.',
    effect: 'offlineEfficiency',
    perLevel: 0.08,
    baseCost: 3,
    costGrowth: 1.8,
    maxLevel: 8,
    icon: '☾',
  },
  {
    id: 'offline-cap',
    name: 'Deep Reserves',
    description: '+4h offline income cap per level.',
    effect: 'offlineCap',
    perLevel: 4,
    baseCost: 4,
    costGrowth: 1.9,
    maxLevel: 10,
    icon: '⧗',
  },
  {
    id: 'cheaper-levels',
    name: 'Efficient Assembly',
    description: '−4% level cost growth compounding per level (softens walls).',
    effect: 'cheaperLevels',
    perLevel: 0.04,
    baseCost: 8,
    costGrowth: 2.6,
    maxLevel: 8,
    icon: '⟐',
  },
  {
    id: 'keep-energy',
    name: 'Echo Capacitor',
    description: 'Keep 5% of your energy through Rebirth per level.',
    effect: 'keepEnergy',
    perLevel: 0.05,
    baseCost: 10,
    costGrowth: 2.8,
    maxLevel: 5,
    icon: '⟳',
  },
  {
    id: 'auto-collect',
    name: 'Autonomous Harvest',
    description: 'Unlock automatic pulse collection and anomaly capture.',
    effect: 'unlockAutoCollect',
    perLevel: 1,
    baseCost: 8,
    costGrowth: 1,
    maxLevel: 1,
    icon: '⤓',
  },
  {
    id: 'auto-buy',
    name: 'Assembler Protocol',
    description: 'Unlock automatic level purchasing for the selected strategy.',
    effect: 'unlockAutoBuy',
    perLevel: 1,
    baseCost: 15,
    costGrowth: 1,
    maxLevel: 1,
    requires: 'auto-collect',
    icon: '⚙',
  },
  {
    id: 'unlock-quantum',
    name: 'Rift Containment',
    description: 'Unlock the unstable Quantum Rift cell.',
    effect: 'unlockQuantum',
    perLevel: 1,
    baseCost: 25,
    costGrowth: 1,
    maxLevel: 1,
    icon: '⬡',
  },
  {
    id: 'extra-slots',
    name: 'Lattice Expansion',
    description: 'Permanently start with +1 unlocked grid slot per level.',
    effect: 'extraSlots',
    perLevel: 1,
    baseCost: 20,
    costGrowth: 3,
    maxLevel: 4,
    icon: '▦',
  },
  {
    id: 'auto-rebirth',
    name: 'Eternal Recurrence',
    description: 'Unlock automatic Rebirth at a fragment threshold you choose.',
    effect: 'unlockAutoRebirth',
    perLevel: 1,
    baseCost: 60,
    costGrowth: 1,
    maxLevel: 1,
    requires: 'auto-buy',
    icon: '∞',
  },
];

export const REBIRTH_UPGRADE_MAP: Record<string, RebirthUpgrade> = Object.fromEntries(
  REBIRTH_UPGRADES.map((u) => [u.id, u]),
);
